### ISSUE TITLE
Bug - NNC out of area cases not sending forward to WNC (caused by bot thinking case is already a WNC case)

### ISSUE THREAD

**Issue by MeganCrowthers** [FutureNorthants/VirtualWorker#149]
**Bug description**
Not all queries that are defined as WNC are forwarding to Megan.Crowthers@westnorthants.gov.uk or displaying the forwardee within CXM. Customer just receives confirmation and case is closed. 

 

**Reference number(s)**
In live

Reference | Submitted | Status | EMN Council | EMN Service Area | 
-- | -- | -- | -- | -- | 
EMN001698 | 01/05/2021 | Case Closed | Northampton | Environmental Health |   
EMN001699 | 01/05/2021 | Case Closed | Northampton | Housing Applications |  
EMN001748 | 03/05/2021 | Case Closed | Northampton | Elections | 
EMN001901 | 05/05/2021 | Case Closed | Northampton | Jobs | 
EMN001930 | 06/05/2021 | Case Closed | Northampton | District Waste |
EMN001960 | 06/05/2021 | Case Closed | Northampton | Environmental Health |
EMN002027 | 07/05/2021 | Case Closed | Northampton | Housing Applications |   
EMN002037 | 08/05/2021 | Case Closed | Northampton |  
EMN002086 | 09/05/2021 | Case Closed | Northampton | District Waste |
EMN002112 | 10/05/2021 | Case Closed | Northampton | Housing Options |   
EMN002134 | 10/05/2021 | Case Closed | Northampton |   |
EMN002153 | 11/05/2021 | Case Closed | Northampton | |
EMN002160 | 11/05/2021 | Case Closed | Northampton | Environmental Health | 
EMN002167 | 11/05/2021 | Case Closed | Northampton |   | 
EMN002168 | 11/05/2021 | Case Closed | Northampton | Environmental Health |  
EMN002189 | 11/05/2021 | Case Closed | Northampton | Revenues | 
EMN002206 | 11/05/2021 | Case Closed | Northampton | Revenues | 
EMN002246 | 12/05/2021 | Case Closed | Northampton | Environmental Health | 
EMN002263 | 12/05/2021 | Case Closed | Northampton |   
EMN002274 | 12/05/2021 | Case Closed | Northampton | Environmental Health | 
EMN002295 | 13/05/2021 | Case Closed | Northampton |   
EMN002296 | 13/05/2021 | Case Closed | Northampton | Environmental Health |
EMN002365 | 14/05/2021 | Case Closed | Northampton | District Waste | 
EMN002407 | 15/05/2021 | Case Closed | Northampton | COVID |  
EMN002460 | 17/05/2021 | Case Closed | Northampton | District Waste | 
EMN002502 | 17/05/2021 | Case Closed | Northampton |   | 
EMN002519 | 17/05/2021 | Case Closed | Northampton | Environmental Health | 
EMN002522 | 17/05/2021 | Case Closed | Northampton |   | 
EMN002579 | 18/05/2021 | Case Closed | Northampton | Environmental Health | 
EMN002588 | 18/05/2021 | Case Closed | Northampton |   |
EMN002619 | 19/05/2021 | Case Closed | Northampton | Environmental Health | 
EMN002622 | 19/05/2021 | Case Closed | Northampton | District Waste | 
EMN002691 | 20/05/2021 | Case Closed | Northampton | Environmental Health |  
EMN002744 | 21/05/2021 | Case Closed | Northampton | Environmental Health |  
EMN002769 | 21/05/2021 | Case Closed | Northampton | Revenues | 
EMN002772 | 21/05/2021 | Case Closed | Northampton |   |   
EMN002805 | 23/05/2021 | Case Closed | Northampton | Parking | 
EMN002820 | 23/05/2021 | Case Closed | Northampton | Environmental Health |   
EMN002904 | 24/05/2021 | Case Closed | Northampton |   |  
EMN002995 | 25/05/2021 | Case Closed | Northampton | Environmental Health |  
EMN003010 | 25/05/2021 | Case Closed | Northampton | COVID |
EMN003038 | 26/05/2021 | Case Closed | Northampton |   | 
EMN003165 | 27/05/2021 | Case Closed | Northampton | Environmental Health | 
EMN003168 | 27/05/2021 | Case Closed | Northampton | Parking | 
EMN003193 | 28/05/2021 | Case Closed | Northampton | Environmental Health | 
EMN003250 | 29/05/2021 | Case Closed | Northampton | Environmental Health | 
EMN003277 | 31/05/2021 | Case Closed | Northampton |   | 
EMN003295 | 01/06/2021 | Case Closed | Northampton | Environmental Health | 
EMN003304 | 01/06/2021 | Case Closed | Northampton | Environmental Health | 
EMN003316 | 01/06/2021 | Case Closed | Northampton | Environmental Health | 
EMN003379 | 02/06/2021 | Case Closed | Northampton |   | 
EMN003380 | 02/06/2021 | Case Closed | Northampton | Environmental Health | 
EMN003397 | 02/06/2021 | Case Closed | Northampton | Environmental Health | 
EMN003416 | 02/06/2021 | Case Closed | Northampton | Events | 
EMN003421 | 02/06/2021 | Case Closed | Northampton | Environmental Health | 
EMN003443 | 03/06/2021 | Case Closed | Northampton | Parking | 
EMN003486 | 03/06/2021 | Case Closed | Northampton |   | 
EMN003508 | 04/06/2021 | Case Closed | Northampton |   | 
EMN003509 | 04/06/2021 | Case Closed | Northampton | Environmental Health | 
EMN003586 | 07/06/2021 | Case Closed | Northampton | Flytipping | 
EMN003628 | 07/06/2021 | Case Closed | Northampton | Freedom of Information | 
EMN003646 | 08/06/2021 | Case Closed | Northampton |   |   
EMN003655 | 08/06/2021 | Case Closed | Northampton | COVID | 
EMN003670 | 08/06/2021 | Case Closed | Northampton |   |   
EMN003672 | 08/06/2021 | Case Closed | Northampton |   | 
EMN003692 | 08/06/2021 | Case Closed | Northampton | Not Found | 
EMN003694 | 08/06/2021 | Case Closed | Northampton | Environmental Health |  
EMN003711 | 08/06/2021 | Case Closed | Northampton | Parking | 
EMN003714 | 08/06/2021 | Case Closed | Northampton | Environmental Health | 
EMN003718 | 09/06/2021 | Case Closed | Northampton | Environmental Health | 
EMN003739 | 09/06/2021 | Case Closed | Northampton | Environmental Health | 
EMN003767 | 09/06/2021 | Case Closed | Northampton | District Waste | 
EMN003768 | 09/06/2021 | Case Closed | Northampton |   | 
EMN003808 | 10/06/2021 | Case Closed | Northampton |   | 
EMN003834 | 10/06/2021 | Case Closed | Northampton | Flytipping | 
EMN003856 | 11/06/2021 | Case Closed | Northampton | Environmental Health | 
EMN003865 | 11/06/2021 | Case Closed | Northampton | District Waste | 
EMN003889 | 12/06/2021 | Case Closed | Northampton |   | 
EMN003917 | 13/06/2021 | Case Closed | Northampton | Planning | 
EMN003923 | 13/06/2021 | Case Closed | Northampton | Environmental Health | 
EMN003926 | 13/06/2021 | Case Closed | Northampton | COVID |
EMN003929 | 13/06/2021 | Case Closed | Northampton | Environmental Health | 
EMN004004 | 14/06/2021 | Case Closed | Northampton | COVID |
EMN004063 | 15/06/2021 | Case Closed | Northampton | Environmental Health | 
EMN004111 | 15/06/2021 | Case Closed | Northampton |   | 
EMN004158 | 16/06/2021 | Case Closed | Northampton | Street Cleansing | 
EMN004163 | 16/06/2021 | Case Closed | Northampton |   | 
EMN004199 | 16/06/2021 | Case Closed | Northampton | Environmental Health | 
EMN004228 | 17/06/2021 | Case Closed | Northampton |   | 
EMN004230 | 17/06/2021 | Case Closed | Northampton | Environmental Health | 
EMN004326 | 18/06/2021 | Case Closed | Northampton |   | 
EMN004400 | 19/06/2021 | Case Closed | Northampton | District Waste | 
EMN004441 | 21/06/2021 | Case Closed | Northampton |   | 
EMN004443 | 21/06/2021 | Case Closed | Northampton |   | 
EMN004466 | 21/06/2021 | Case Closed | Northampton | Environmental Health | 
EMN004477 | 21/06/2021 | Case Closed | Northampton | Environmental Health |

Queries that have been received 
Reference | Submitted | Status | EMN Council | EMN Service Area | 
-- | -- | -- | -- | -- | 
EMN004421 | 20/06/2021 | Case Closed | Northampton | Revenues | 
EMN004280 | 18/06/2021 | Case Closed | Northampton | Revenues | 
EMN004177 | 16/06/2021 | Case Closed | Northampton | Revenues | 
EMN004139 | 16/06/2021 | Case Closed | Northampton | Not Found | 
EMN004045 | 15/06/2021 | Case Closed | Northampton | Revenues | 
EMN003967 | 14/06/2021 | Case Closed | Northampton | Leisure |  
EMN003766 | 09/06/2021 | Case Closed | Northampton | Benefits | 
EMN003174 | 28/05/2021 | Case Closed | Northampton | Revenues | 
EMN003244 | 29/05/2021 | Case Closed | Northampton | Housing Applications | 
EMN002958 | 25/05/2021 | Case Closed | Northampton | Revenues | 
EMN002835 | 24/05/2021 | Case Closed | Northampton | Revenues | 
EMN002870 | 24/05/2021 | Case Closed | Northampton | Revenues | 
 
If you can - please attempt to replicate the error(s) in test and provide the TEST reference number.
Replicated in Test under EMN000699

**Bug reproduction**
Steps to reproduce the behaviour:
1. Go to North Test Contact Us Site
2. Select EVH as your query type 
3. Put in your query 
4. Set your address as out of area 
5. Submit Form
5. See error case closes without forwarding

 

**Expected behaviour**
When a customer inputs a WNC address the query automatically diverts to WNC. (Megan.Crowthers@westnorthants.gov.uk)
 

**Screenshots**
Example:
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/78955180/122930375-db55fa00-d363-11eb-98ff-a475d52b9b46.png">
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/78955180/122930473-ee68ca00-d363-11eb-8a21-b09679609423.png">
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/78955180/122930546-fd4f7c80-d363-11eb-9013-2a067457c1f7.png">
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/78955180/122930608-093b3e80-d364-11eb-8813-6a37582acf6b.png">

 

**Additional comments**
On our investigations it looks like the only emails that are getting to you are for service area’s: Revenues, Benefits, Housing Options, Housing Applications, Not Found & Leisure

**Comment by Sadie-hub** [comment]
Tested in UAT EMN702-707, Tested in Live EMN4893-4896
