### ISSUE TITLE
Feature Request - Location priority list for NNC

### ISSUE THREAD

**Issue by MeganCrowthers** [FutureNorthants/VirtualWorker#150]
**User Story/Requirement**
Norbert to only suppress the email forward if the bot is running in the West.

**Is the feature request related to an existing problem? Please describe.**
The fix would be to change the order at which we scan for locations depending on if it's WNC or NNC bot. The WNC is the as-is setup (Northampton, South Northants, Daventry, Wellingborough, Kettering, Corby, East Northants) the first area in the list which finds a match wins

**Describe the solution you want to be used**

Order for BOT to ascertain Sovereign (Provided by NNC) 

•    Wellingborough
•    Kettering
•    Corby
•    East Northants
•    South Northants
•    Daventry
•    Northampton

 

**Describe alternatives you have considered**
N/A

 

**Additional comments**
N/A

 

**Acceptance Criteria***
Send an email referencing Eastfield as the location - confirm this sends to Wellingborough.

**Comment by Sadie-hub** [comment]
Tested in UAT EMN709-EMN714 - All ok where town mentioned.
Tested 'Eastfield' EMN000715 - Still allocating to Northampton instead of Wellingborough

**Comment by Sadie-hub** [comment]
1/7 Re-tested 'Eastfield' EMN000716 - successfully allocated to Wellingborough

**Comment by Sadie-hub** [comment]
Re tested in live EMN005370 - EMN005377 - all ok apart from EMN005374 which redirected to the West in error. The email text was 'Please can you advise me on waste in north Northamptonshire' 
Is there anyway we can add the phrase 'North Northamptonshire' without Norby reading 'Northampton'?

**Comment by lfayter** [comment]
NNC - Raised a few additional test cases in Live:-
EMN005987 and 5989 - both directed correctly.
EMN005988 failed - using the wording 'north Northamptonshire', was incorrectly directed to WNC.

**Comment by lfayter** [comment]
NNC - I tried replicating EMN005988 in UAT but Norbert deals with it differently, it's moving the case to ALC (EMN000809) - which is better than it going to the West.  I tried replicating it a further 4 times (810-813), slightly different wording, but each time it went to ALC.

**Comment by lfayter** [comment]
NNC - Retested in live to see if the case was dealt with the same as in UAT (see above update) - but it was sent to WNC again, the same as before (EMN006054).

**Comment by Sadie-hub** [comment]
![image](https://user-images.githubusercontent.com/82212242/128693406-393b883f-0f28-46f4-924e-818a264c3867.png)

**Comment by Sadie-hub** [comment]
![image](https://user-images.githubusercontent.com/82212242/128693477-fd62817b-8e6b-4058-90ab-cece39051e7b.png)

**Comment by lfayter** [comment]
Decision made that the process that currently happens in UAT will be moved over to live.   Emails received that contain 'North Northamptonshire' will go to 'Awaiting Location Confirmation'.  Confirmed on Teams also.

**Comment by lfayter** [comment]
NNC Live Testing:-
EMN007051 (2.24 pm) - Form submission - 'North Northamptonshire' specified within enquiry details.  No address specified.  Case went to ALC, replied to auto response with 'Kings Cliffe, North Northants'.  Case went back to 'Hub-Awaiting Review'.  

EMN007053 (2.37 pm) - Form submission - 'North Northamptonshire' specified within enquiry details.  No address specified.   Case went to ALC, replied to auto response with 'Kings Cliffe'.  Case still went to 'Hub-Awaiting Review'

EMN007056 (3.06 pm) - Form submission - 'North Northamptonshire' specified within enquiry details.  Bulwick address selected.  Case allocated to correct sovereign council, email received.  Case closed.

EMN007057 (3.21 pm)  - Email submission - 'North Northamptonshire' specified within enquiry details.  No address specified.   Case went to ALC, replied to auto response with 'Bulwick'.  Case allocated to correct sovereign council, email received.  Case closed.

EMN007059 (3.34 pm) - Form submission - 'North Northamptonshire' specified within enquiry details.  No address specified.  Case went to ALC, replied to auto response with 'Bulwick'.  Case allocated to correct sovereign council, email received.  Case closed.

When it's a form submission, on the sovereign council email template we've noticed the original enquiry is not  appearing on the email body.  The update appears on the email, but you then have to click into the attachment to view the original enquiry.   When it's an email submission, both the original enquiry and update appear on the email body of the sovereign council email template.

**Comment by lfayter** [comment]
Above testing took place yesterday, 9/8/21

**Comment by Sadie-hub** [comment]
Missing from Dynamo table:

- Kings Cliffe
- Laxton

Spelling mistake Brigstock

**Comment by MeganCrowthers** [comment]
@Sadie-hub just to confirm what Areas as Kings Cliffe and Laxton and Brigstock in? Kettering, East Northants, Welly or Corby ?

**Comment by Sadie-hub** [comment]
@MeganCrowthers All East Northants

**Comment by MeganCrowthers** [comment]
@Sadie-hub all done and ready for testing

**Comment by AndyBoatwright** [comment]
@lfayter the section re the enquiry details from forms and emails I've copied and pasted that off this bug and into the thread for #91 ; the reason is that its otherwise awkward to close bug/enhancement issues off if extra bits are included on the wrong one, plus we lose track of stuff if its been tagged on the wrong thread.

**Comment by lfayter** [comment]
NNC Live Testing - Tested Dynamo additions/amendments - Kings Cliffe, Laxton, Brigstock.  All cases worked fine:-

Kings Cliffe - EMN007367 (form), EMN007385 (email) 
Laxton - EMN007374 (form), EMN007386 (email)
Brigstock - EMN007373 (form), EMN007375 (email)

**Comment by MeganCrowthers** [comment]
Fab - marked as Signed off and now live 😄

**Comment by MeganCrowthers** [comment]
@lfayter sorry can you do same tests in live for me please - just to triple check its all working 😄

**Comment by lfayter** [comment]
NNC Live Testing:-
EMN007390 (form) - 'North Northamptonshire' mentioned in enquiry details.  'Laxton Road, Bulwick' selected as customer address.  Correct sovereign council allocated, all emails received, case closed.
EMN007391 (email) - 'North Northamptonshire' mentioned in email body.  'Bulwick' specified in subject.  Correct sovereign council allocated, all emails received, case closed.
