### ISSUE TITLE
Feature Request - Change to Formatting on Contact Us Form Submission - Missing Spaces on Contact Us form Submission

### ISSUE THREAD

**Issue by Sadie-hub** [FutureNorthants/VirtualWorker#156]
**User Story/Requirement**
As a customer advisor I would like to receive addresses, that are presented on a new line within the equity details, on a contact us form in a readable format. 

**Is the feature request related to an existing problem? Please describe**
Yes, EMN000718 as an example in North and EMA003251 as an example in West

**Describe the solution you want to be used**
When the customer completes a Contact Us Form query and they place a 'return' in the body of text the formatting is not recognising the return and grouping the text together.
I.e.
1 Ferndale
Twywell
NN14 3AH

is showing as:

1FerndaleTwywellNN14 3AH  

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/78955180/128177160-51807138-c23a-4f76-be81-b131609d8285.png">

<img width="830" alt="image" src="https://user-images.githubusercontent.com/78955180/128177407-b663e715-0c32-496b-8d77-d6db35c83ecf.png">

**Describe alternatives you have considered**
N/A

**Additional comments**
Example of where this formatting has presented differently in Jadu/Email OutPut to Sovereign - Test case raised in UAT - EMN000718

**Acceptance Criteria**
When a customer completes a contact us form and using a new line (Return Key) to format their query, this passes through Jadu as a readable format.

**Comment by Sadie-hub** [comment]
@MeganCrowthers I have tested 'email' and the spacing is fine in CXM and on the forwarded Sovereign email, so it looks like it's only the form that's being effected - example EMN006705 (3/8 16:22)

**Comment by Sadie-hub** [comment]
Original email (attachment) shows correct spacing
![image](https://user-images.githubusercontent.com/82212242/128694040-793ef4a6-ded4-43f0-915a-ea58d964ee43.png)

**Comment by Sadie-hub** [comment]
Sovereign email - missing spaces
![image](https://user-images.githubusercontent.com/82212242/128694114-174378a8-ec59-4334-9bdb-7ba74ad9387e.png)

**Comment by Sadie-hub** [comment]
@MeganCrowthers we have tested this and are happy for it to move on, do you still need to test in the West?

**Comment by MeganCrowthers** [comment]
Tested in West Instance - CXM and Email displaying "spaces" correctly. Testing Example EMA003291.

**Comment by MeganCrowthers** [comment]
Tested for west in live under EMA020712. Working as expected.

**Comment by lfayter** [comment]
NNC Testing - Live:-
EMN007694 - working as expected.
