### ISSUE TITLE
Bug - Hide any legal blurb received in customer contact

### ISSUE THREAD

**Issue by MeganCrowthers** [FutureNorthants/VirtualWorker#16]
**Bug description**
When a query is sent which contains legal blurb this is being put into Jadu making is hard for Norbert to transfer to correct sovereign/service area and harder for Soverigns to read.
 

**Reference number(s)**
Awaiting for NNC to put reference numbers in here. This seems to be an issue for contact made by ENC.

**Bug reproduction**
Steps to reproduce the behaviour:
1. Send an email to contactus@northnorthants.gov.uk from an ENC email address
2. see error

 

**Expected behaviour**
When you submit a query where you signature holds legal blurb this is tripped from being read in the process.

 

**Screenshots**
If applicable, add screenshots to help explain the issue.

 

**Additional comments**
Add any other commentary about the problem here.

**Comment by MeganCrowthers** [comment]
Can we remove Legal Blurb from this customer EMA010571 example 

Ashleigh Cleaver

Control Hub Administrator

Northamptonshire Highways

Highways Depot, Harborough Road, Brixworth, Northamptonshire, NN6 9BX

DDI: +44(0)1604 651075

Web: www.kierwsp.co.uk<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.kierwsp.co.uk%2F&data=02%7C01%7CNRSWA-S81%40anglianwater.co.uk%7C05f1687daad345feafb808d6cfd3abd5%7Ce7ba1d022aa248d58185e3dc6bf7b86d%7C0%7C0%7C636924905363639378&sdata=smnIam2GfAPoMYzAdBs26MbvJt3QB0ele9iRYRABYPs%3D&reserved=0>;;

To ensure any enquiries are dealt with correctly and to report defects please use our online Street Doctor service. This process means all issues are recorded.

Once reported you will be issued with a unique reference number and be able to follow the progress of your enquiry.

• Website: www.northamptonshire.gov.uk/streetdoctor<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.northamptonshire.gov.uk%2Fstreetdoctor&data=02%7C01%7CNRSWA-S81%40anglianwater.co.uk%7C05f1687daad345feafb808d6cfd3abd5%7Ce7ba1d022aa248d58185e3dc6bf7b86d%7C0%7C0%7C636924905363639378&sdata=%2BZdwLPisvWMoswJ1Q4OmNdJ8ivXDUBVH3d1646R6KR0%3D&reserved=0>;

• For information and transport and highway updates follow us on Twitter @nnhighways

• To view road works and diversion routes go to roadworks.org

[cid:image001.jpg@01D31B21.D071B560]

[cid:image017.jpg@01D4ACC9.FE335D10]

CONFIDENTIAL

This e-mail is confidential to the named recipient. If you have received a copy in error, please destroy it. You may not use or disclose the contents of this e-mail to anyone, nor take copies of it.

The only copies permitted are (1) by the named recipient and (2) for the purposes of completing successful electronic transmission to the named recipient and then only on the condition that these copies, with this notice attached, are kept confidential until destruction.

Kier Integrated Services Limited. Tempsford Hall, Sandy, Bedfordshire, SG19 2BD. Registered in England No. 873179 www.kier.co.uk<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.kier.co.uk&data=02%7C01%7CNRSWA-S81%40anglianwater.co.uk%7C05f1687daad345feafb808d6cfd3abd5%7Ce7ba1d022aa248d58185e3dc6bf7b86d%7C0%7C0%7C636924905363649388&sdata=%2BkS%2FKVIV8%2FVr5vPnXhOTuBaHZRRfABfCpSeuXsynuz4%3D&reserved=0>;

WSP UK Limited, WSP House, 70 Chancery Lane, London, WC2A 1AF. Registered in England No. 01383511 www.wsp.com<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.wsp.com&data=02%7C01%7CNRSWA-S81%40anglianwater.co.uk%7C05f1687daad345feafb808d6cfd3abd5%7Ce7ba1d022aa248d58185e3dc6bf7b86d%7C0%7C0%7C636924905363659392&sdata=9v4XOjjDX4zAmfJusaaxUGrVelwU9%2FnZQgrPoTiMNPk%3D&reserved=0>;

**Comment by MeganCrowthers** [comment]
@KevinWhite most recent examples for #16 for NNC
EMN005031 (1/7/21 15:32), EMN004997 (30/6/21 20:52), EMN004989 (30/6/21 17:52), EMN004878 (28/6/21 20:17), EMN004765 (26/6/21 18:45) EMN004989 30/6/21 17:52 EMN005054 - raised today

All in live environment.

**Comment by MeganCrowthers** [comment]
Example in NNC UAT = EMN000717

**Comment by GiftyBecks** [comment]
More investigation required on this one - Need to check if North can add something like 'kind regards' to their email signature.

**Comment by Sadie-hub** [comment]
EMN005301 - example of legal blurb from a customer email address

**Comment by AndyBoatwright** [comment]
Some of this is due to the Sigparser not performing as expected; other instances are due to the "fluid" nature of the signatures being used which prevents an accurate determination of where the signature actually begins so that it can be removed successfully; to be investigated.

**Comment by AndyBoatwright** [comment]
More recent examples of the most problematic ones to be provided to enable us to check and address.

**Comment by MeganCrowthers** [comment]
This is no longer an issue
