### ISSUE TITLE
Customer confirmation emails failing in UAT

### ISSUE THREAD

**Issue by Sadie-hub** [FutureNorthants/VirtualWorker#160]
**Bug description**
Error with customer confirmation emails failing to send 

**Reference number(s)**
EMN000742

**Bug reproduction**
Steps to reproduce the behaviour:
1. Submit Contact Us Form
2. Case created in CXM
3. Bot to forward to relevant sovereign
4. Confirmation email sent to customer

**Expected behaviour**
A confirmation email to be sent to the customers email address

 **Screenshots**
![image](https://user-images.githubusercontent.com/82212242/125070277-a65ddd00-e0af-11eb-9276-dc034a9203b6.png)
 

**Additional comments**
This has now been resolved

**Comment by MeganCrowthers** [comment]
@lfayter are you able to give us an example of this please

**Comment by Sadie-hub** [comment]
Tested 15:06 EMN000818 & EMN00089 - all appears to be working now
