### ISSUE TITLE
Bug - BOT not picking up authority for certain postcodes:

### ISSUE THREAD

**Issue by MeganCrowthers** [FutureNorthants/VirtualWorker#18]
NN71LU - BOT = Northampton should be South Northants

**Comment by MeganCrowthers** [comment]
Response to location confirmation - NN11 0FW Barley Close - BOT = Unsure - should be Daventry. 
(Create intent/utterance for this response? As customer may add additional information onto this response which could change the direction/service the email needs to go through to)

**Comment by AndyBoatwright** [comment]
This is probably down to the data the bot is using for the postcode checker not including NN11 under Daventry; @KevinWhite can probably confirm if this is the case?

**Comment by Savannah-Marie** [comment]
NN7 1HP - Picking up as Northampton but should be South Northamptonshire Council

**Comment by Savannah-Marie** [comment]
NN6 0PJ - picking up as Northampton but should be Wellingborough Borough Council

**Comment by Savannah-Marie** [comment]
(EMA002115) NN7 1LU - picking up as Northampton but should be South Northamptonshire Council

**Comment by AndyBoatwright** [comment]
See also [Issue#35](https://github.com/FutureNorthants/VirtualWorker/issues/35)

**Comment by MeganCrowthers** [comment]
API needs changing - postcode issues no longer a problem
