### ISSUE TITLE
Bug - Archived emails causing forwarding to fail

### ISSUE THREAD

**Issue by MeganCrowthers** [FutureNorthants/VirtualWorker#183]
**Bug description**
When a query is more than 7 days old the query does not forward 

 

**Reference number(s)**
EMN006350 (16:26) 

 

**Bug reproduction**
Steps to reproduce the behaviour:
1. Send email 
2. Remove email from log 
3. See error

 

**Expected behaviour**
If an email is less than 30 days old the email will send - if not query goes to Unitary awaiting review with message to deal with manually

**Comment by MeganCrowthers** [comment]
Tested for North under EMN000848 case moved to Unitary Awaiting Review as expected but not displaying the failed to forward text

**Comment by MeganCrowthers** [comment]
Tried replicating under EMN000853 however unable to get "Failed to Forward" to view

**Comment by MeganCrowthers** [comment]
Tested in North under EMN000855 to replicate an email over 30 days old. Query now confirms that it has failed forward. 
<img width="1333" alt="Screenshot 2021-08-19 at 10 46 16" src="https://user-images.githubusercontent.com/78955180/130047747-1d746bae-3a3e-46d9-ba2e-dd75013eca77.png">

**Comment by MeganCrowthers** [comment]
Agreed wording: "This enquiry is more than 30 days old and has been archived. Please copy the original message and updates and forward onto the Sovereign Council via Outlook, quoting the email reference number"

**Comment by MeganCrowthers** [comment]
@Sadie-hub @lfayter @joanne-debug 

Please can you have a look at EMN000860, EMN000862 and EMN000863.

These are 2 tests I have put through. This is what will happen is a query is more than 30 days old and has been unable to automatically forward to query to our colleagues. 

If you are happy with the tests, please add the label "North Signed Off" using the labels on right hand side of the page.

**Comment by MeganCrowthers** [comment]
Tested for West Under EMA003297, EMA003298 and EMA003299 

All working as expected.

**Comment by Sadie-hub** [comment]
@MeganCrowthers this looks great, only one small thing as we are unable to use capitals please could we have a commar after archived instead of a full stop? If this is a lot of work don't worry.

**Comment by MeganCrowthers** [comment]
@Sadie-hub have asked Kev so will get back to you and let you know 😄

**Comment by Sadie-hub** [comment]
Moved to signed off -north as full stop purely cosmetic.

**Comment by lfayter** [comment]
EN Test:  Tried to forward 3 test cases in UAT and all worked as expected.   Test cases EMN000853 (originally raised on the 19/8/21), EMN000870 (originally raised on the 31/8/21) and EMN000869 (originally raised on the 27/8/21).   The statement appeared advising me on all 3 cases, the cases then returned to 'Hub - Awaiting Review).  

Also forwarded a recent test case (EMN000876 - originally created on the 24/9/21) to make sure the above statement didn't appear.  That worked as expected.  Case forwarded to sovereign council.

**Comment by lfayter** [comment]
EN Test - 2 test email submissions raised (about to test #36 - EMN000877 and EMN000878) and the above statement, 'this enquiry is more than 30 days', appeared and both cases went to 'Hub - Awaiting Review'.  Details also added to Teams.

**Comment by lfayter** [comment]
EN Test

EMN000881 - Retested.  Email sent to unitary-test@northnorthants.chat, statement no longer appears.

**Comment by lfayter** [comment]
19/10/21 - Expiry of emails amended from 7 days to 30 (KW).
