### ISSUE TITLE
Feature - Fix my street queries to automatically raise in systems

### ISSUE THREAD

**Issue by MeganCrowthers** [FutureNorthants/VirtualWorker#24]
**User Story/Requirement**
I want to be able to report issues on Fix My Street and these queries be received by the Sovereign. 

 

**Is the feature request related to an existing problem? Please describe.**
Enhancement to https://github.com/FutureNorthants/VirtualWorker/issues/23 

 

**Describe the solution you want to be used**
Customer reports fix my street online
Issue reports directly into the system without the needs for a human re raise
Reference and SLA's auto sent out to the customer

 

**Describe alternatives you have considered**
Not use Fit My Street at all - make customers go right way
 

**Acceptance Criteria***
When I submit a request to Fix My Street I also receive a action case reference from the Soviergn as my case has been directly loaded into the system.

**Comment by MeganCrowthers** [comment]
<img width="793" alt="Screenshot 2021-07-07 at 09 27 42" src="https://user-images.githubusercontent.com/78955180/124727073-47a92f80-df06-11eb-8c87-007d3b4e5720.png">

**Comment by MeganCrowthers** [comment]
<img width="672" alt="Screenshot 2021-07-06 at 10 39 05" src="https://user-images.githubusercontent.com/78955180/124727430-9ce54100-df06-11eb-9b4d-cbc17a3db414.png">
Categories within the Repot it Form:

Abandoned vehicles - OAS (E.L.V.IS)
Bus Stops (OAS)
Car parks (OAS/DISTRICT)
Crash Barriers - Damaged / Missing (OAS/DISTRICT)
Dog fouling - District
Drain Covers - OAS/District
Drains - PAS/District
Flyposting - District
Flytipping - District
Footway/Footpath - OAS
Graffiti - District
Highway Bridges - Damaged/Unsafe - OAS
Kerbs - OAS
Parks/landscapes - District
Pedestrian Barriers - Damaged / Missing - OAS
Public toilets - District
Rights of Way - OAS
Road Markings - Worn/Faded - OAS
Roads - OAS
Rubbish (refuse and recycling) - District
Safety Bollard - Damaged/Missing - OAS
Sign - OAS
Street cleaning - District
Street light - OAS

oactions are provided with nearest road via map (bing maps) along with co-ordinates.

Category is provided within the email - and is also a part of the subject title.

A photo is also provided as an option

**Comment by MeganCrowthers** [comment]
FixMyStreet does not include all the data we need in its reports
Please get in touch and let us know what is missing.

FixMyStreet routinely includes the following information in its reports:

User's name, email address, and, if given, phone number
Report category [you, the council, may dictate these]
Report title and description
Easting & northing, latitude & longitude
Nearest road to the pin placed on the map (automatically generated by Bing Maps)
Nearest postcode to the pin placed on the map (automatically generated)

**Comment by MeganCrowthers** [comment]
How Dav raise Fix my Street:
Hi Megan
 
In Daventry we receive emails from Fix My Street in our main customer services inbox – customercare.ddc@westnorthants.gov.uk
 
We then log the case on Lagan (CRM) – depending on what it is.  Usually they relate to fly tips so we transfer the case information to a service request on Lagan that then this goes through to the back office (service area) to action.
 
If we have the customer’s contact details we send an email acknowledgement confirming the case has been logged and giving the case reference number.
 
The emails are filed after they have been dealt with.

**Comment by MeganCrowthers** [comment]
North Fix my street

Fix My Street
 
Corby - We cannot do this at Corby without support from Granicus which will come at a cost.
 
Welly - We have these reports come through to us from Fixmystreet. All we do is send the email to Norse, and then let the customer know we’ve received it and where it was sent. Rach Luck said that initially Norse could not access the reports, but our IT department worked with them and they can now. We also have reports come from Lovecleanstreets and we treat these the same.
 
Kettering – How easy/practical depends on what data it will provide and whether that will be sufficient to craft a CRM SR without human oversight. In terms of how the data could be delivered it's easy to provide an endpoint/webhook for it, just have to know what protocol it would use and ideally what authentication scheme.  JWT Auth tokens dynamically sourced from our AAD Tenant rather than application keys by preference as it reduces the possibility the key could be leaked in the event of a MitM attack or similar.
 
I've got an api gateway for the NNC IDOX LLPG and that includes all of the geographical extents for objects and parcels and all of the segments for streets in the zone.  I should be able to work quite effectively with even a pin dropped randomly onto a map (so long as they're sending us the data for it and not just like a picture of the map - that's not useful).  I'd done preliminary work on this way back when Neil and I were talking about accepting geographic map points for fly-tipping requests.  If anything that's easier now as the options via IDOX are amazing v's what the old Northgate system offered.
 
ENC – waiting to hear

**Comment by lfayter** [comment]
ENC - Current Fix My Street Process:-

•  Report comes into our customer services in box.

•  A case is manually created in CXM.  The majority of reports received relate to waste/cleansing and both our waste team and contractors use CXM so the case is managed through the service request process.  (Reports received via 'In My Area/QuestionWhere' are dealt with in the same way).  

•  If the report is relating to a different service area, which is not often, then these reports would be manually forwarded by email to the relevant service area and the customer notified.

**Comment by MeganCrowthers** [comment]
Tests completed:
**Test 1 - Dog Mess** 
EMA003375** - Created case REP001217. 
Case pulled across details of case.

"Enquiry Details" showing as empty message - however original enquiry of problem report displays within Original Message. 
Location of report pulled across as attachment. Query pulling across correct sentiment and setting to correct service area. Case set to awaiting review. 

**Test 2 - Street cleaning** 
EMA003377** - Created REP001218
Case pulled across details of case.

As above.

**Comment by MeganCrowthers** [comment]
Test completed for drain covers - however drain covers details with by Highways.

Case created EMA003431 and created REP case.

<img width="858" alt="image" src="https://user-images.githubusercontent.com/78955180/139685829-f539aca7-3485-4a9c-a774-cebc5b0ea4c6.png">

Case did go to awaiting review after being in case closed status. Further bug.

**Comment by MeganCrowthers** [comment]
Attempted testing however file does not seem to be uploading. @KevinWhite would you be able to have a look at the file sent in slack to confirm if there is anything missed that is causing this to bork?

**Comment by MeganCrowthers** [comment]
Tests completed on all district cases below actions.

**Actions**

- [ ] Once EMA case is raised - query should auto close if this has an REP case attached
- [ ] MC to discuss with CS whether query should be raising as Offensive Graffiti 
- [ ] MC to discuss with CS on Rubbish, Refuse and Recycling 
- [ ] MC to discuss Parks/Landscapes with CS as open to interpretation 
- [ ] MC to clarify offensive flyposting with CS
- [ ] Discuss with @KevinWhite whether some cases can be email i.e street name places as this is no longer an option on report it. 






![image](https://user-images.githubusercontent.com/78955180/143220205-6bdc3609-63be-4b23-93f9-9636c94f7b43.png)

![image](https://user-images.githubusercontent.com/78955180/143220260-d2ee0b31-7c22-4cc7-a3c1-208b4232fe67.png)

![image](https://user-images.githubusercontent.com/78955180/143220288-414e51ce-8936-4f9b-b052-6b64f547d77c.png)

![image](https://user-images.githubusercontent.com/78955180/143220322-e0ab975f-f54b-4eed-9af9-4ff08ea5ea62.png)

![image](https://user-images.githubusercontent.com/78955180/143220357-9e4a9440-bff9-483c-bd3d-fd0c2d4cc2d9.png)

![image](https://user-images.githubusercontent.com/78955180/143220396-8d8f5435-6890-4e66-8466-a3570a55e215.png)

![image](https://user-images.githubusercontent.com/78955180/143220434-2ca79884-de36-423a-ba22-9aa39869d379.png)

![image](https://user-images.githubusercontent.com/78955180/143220537-b8a38eb2-f98d-425c-8dd3-cb0d9d59dc8e.png)
