### ISSUE TITLE
Cases with  confidence less than 95% failing to send confirmation emails to customers or sovs

### ISSUE THREAD

**Issue by AndyBoatwright** [FutureNorthants/VirtualWorker#265]
**Bug description**
Cases below 95 confidence going to ALC, then determines sovereign council, suggests response then is just closing; doesnt forward and shows "failed to send confirmation" on CXM; no emails are sent; this is affecting both sov forwards and customer notifications.
 
**Reference number(s)**
EMN001407;  84% confident; failed to send to Kettering

![image](https://user-images.githubusercontent.com/48676402/197516705-9f9b2e46-9ff5-4dab-8d9f-c01c3e416f26.png)

**Comment by MeganCrowthers** [comment]
Click Up Reference - https://app.clickup.com/t/20492552/MB-792
