### ISSUE TITLE
Strip Legal Blurb for Contact Us Emails

### ISSUE THREAD

**Issue by MeganCrowthers** [FutureNorthants/VirtualWorker#31]
Requirement: To remove legal blurb from the enquiry information when it is forwarded to sovereign authorities 

User story is: As a customer advisor, I want to receive details of the customer enquiry without the accompaniment of any legal blurb - so that I can read the enquiry more easily and so that customers do not have sight of the current format in which advisors receive the enquiry.

Acceptance criteria: When an enquiry is forwarded to sovereign authorities, it is done so without the presence of any legal blurb with the enquiry.

01832 742000 | customerservices@east-northamptonshire.gov.uk<mailto:customerservices@east-northamptonshire.gov.uk>
East Northamptonshire Council Cedar Drive Thrapston Northamptonshire NN14 4LZ

[http://2.bp.blogspot.com/-4rjlRiZM-_k/UL93W_saO4I/AAAAAAAAARs/FueCMD2OXIE/s1600/new_twitter_logo.jpg] Follow us on Twitter: https://twitter.com/ENCouncil

[cid:image002.jpg@01D4C539.72214DE0] Like us on Facebook: https://www.facebook.com/ENCLatestNews/

Please visit our website for online information and services www.east-northamptonshire.gov.uk<http://www.east-northamptonshire.gov.uk>;

Find out all the latest information on coronavirus (COVID-19) - including symptoms, how to avoid spreading germs and the dedicated 111 online coronavirus service - by visiting http://nhs.uk/coronavirus

________________________________
Warning: Although East Northamptonshire Council has taken reasonable precautions to ensure no viruses are present in this e-mail, the Council cannot accept responsibility for any loss or damage arising from the use of this e-mail or attachments.

This e-mail, including any attachments, is intended for the exclusive use of the addressee. Please do not forward without consideration of the origins of the email and any data included within. Please note that this and any responses to this email may be subject to the Freedom of Information Act 2000/Data Protection Act 2018.

Any views or opinions expressed in this e-mail do not necessarily represent those of East Northamptonshire Council and are not to be relied upon without subsequent written confirmation by an authorised representative.

If you are not the addressee any disclosure, reproduction, distribution, forwarding or other dissemination or use is strictly prohibited. If you have received this in error please notify the council's Data Protection Officer via DP@east-northamptonshire.gov.uk

East Northamptonshire Council takes the protection of your personal data seriously. Full details can be found in the council's Privacy Statement
________________________________

**Comment by AndyBoatwright** [comment]
Presume this will need to be done for all authorities as AFAIK we only tailored it for NBC initially and there is an issue if the signatures get changed that it won't necessarily continue to work.

**Comment by MeganCrowthers** [comment]
This has now been closed as this has been completed

**Comment by MeganCrowthers** [comment]
Requirement: To remove legal blurb from the enquiry information when it is forwarded to sovereign authorities - My understanding of 
User story is: As a customer advisor, I want to receive details of the customer enquiry without the accompaniment of any legal blurb - so that I can read the enquiry more easily and so that customers do not have sight of the current format in which advisors receive the enquiry. 
Acceptance criteria: When an enquiry is forwarded to sovereign authorities, it is done so without the presence of any legal blurb with the enquiry.

**Comment by MeganCrowthers** [comment]
Case closed - Legal Blurb from ENC covered in https://github.com/FutureNorthants/VirtualWorker/issues/16
