### ISSUE TITLE
Feature Request - "Links" to be activated on forwarded email hub email

### ISSUE THREAD

**Issue by MeganCrowthers** [FutureNorthants/VirtualWorker#36]
**User Story/Requirement**
As a customer advisor, I want to easily transfer misdirected contact to the correct sovereign/ department or refer back to the email hub so that the query can be dealt with by the correct team.

**Acceptance Criteria***
When the sovereign authority receives a customer query, they are presented with links within the email that enables them to select the appropriate link if incorrectly handled.

**Is the feature request related to an existing problem? Please describe.**
No, however we currently are not able to report on queries incorrectly behind handler by Norbert. 

**Describe the solution you want to be used**
Ability for Sovereign forwards to be quickly sent to the appropriate area using a series of links within the Norbert forward. Also, to report on queries that have been incorrectly triaged and to enable sovereign authorities to submit the case to either the correct authority or back to the mail hub for re distribution.

<img width="543" alt="image" src="https://user-images.githubusercontent.com/78955180/128169424-bb5f6afe-7d6c-45b5-9415-dd8784680728.png">
 

**Additional comments**

- How can we report on this?
- How can we get this linked to Trello for updates?
- Additional Option to "Send to Email Hub" - Option for when agent does not know where query needs to go to 

 
**Testing Instructions** <i>Process may change dependent on development options</I>

1. Send an email from your own personal account to unitary-test@northampton.digital for west or contactus-test@northnorthants.digital for North
2. Set your subject to what your query is regarding
3. In the body of the message input your query - this could be anything council related. Remember to input a location using either a postcode, town or area.
4. Wait for the email to transition in CXM 
5. The "Sovereign" will then receive an email with the customers query
6. Get the "Sovereign" to select one of the links from within the template to send to another sovereign 
7. Check CCXM to see if the route has been replicated in CXM (Confirming Sovereign has been changed and query has now been sent)
8. Check new sovereign has received the email

**Comment by MeganCrowthers** [comment]
Requirement: Ability to report on queries that have been incorrectly triaged and to enable sovereign authorities to submit the case to either the correct authority or back to the mail hub for re distribution. 

User story is: As a customer advisor, I want to receive details of the customer enquiry and if incorrectly handled - easily transfer to the correct sovereign or refer back to the email hub.

Acceptance criteria: When the sovereign authority receives a customer query, they are presented with links within the email that enables them to select the appropriate link if incorrectly handled.

**Comment by MeganCrowthers** [comment]
Discuss with Devs how this will link with Trello

**Comment by MeganCrowthers** [comment]
<img width="643" alt="Screenshot 2021-07-07 at 09 28 48" src="https://user-images.githubusercontent.com/78955180/124726603-ce114180-df05-11eb-9dde-cf979c4b78b1.png">

**Comment by MeganCrowthers** [comment]
Request from West CS Meeting for Sovereigns to be named as:
Guildhall Hub
Lodge Road Hub
One Angel Square Hub
The Forum Hub

Just for reference:

Guildhall Hub is NBC
Lodge Road Hub is Daventry
One Angel Square Hub is NCC (OAS)
The Forum Hub is South Northants

**Comment by MeganCrowthers** [comment]
Tested under EMA003358,EMA003359, EMA003360.

**Comment by lfayter** [comment]
EN Testing (UAT):-

Unable to test exactly as it suggests in Github as the 2 email submissions I raised earlier (877 and 878) are stuck in a loop - as soon as I try to forward them they fail and just loop back to 'Hub - Awaiting Review'.  

I tried using a form submission case that already existed in CXM (EMN000873).  The case was in a 'Closed' status, I then forwarded it to 'Kettering' - the sovereign council email came through fine.  I selected the link to Corby on the sovereign email - the redirect page appeared notifying me that my case had been transferred, the CXM dashboard updated but I received 2 sovereign emails in our test gmail account - I was only expecting one.  

I then raised a new form submission (EMN000879 4.27 pm).  When the 1st sovereign email came through (for East Northants area) I then selected the Corby link on that one.  The redirect page appeared notifying me that my case had been transferred to Corby.  The CXM dashboard did update to a degree - no 'forwarded to email' appeared on the timeline and no email was received in our test gmail account.

**Comment by lfayter** [comment]
EN Re-Test

EMN000881 - New email sent.  Correct sovereign Council and service area allocated.  Customer auto response and sovereign council email received.   On original sovereign council email, link for 'Kettering' selected.  The 'successfully transferred' notice appears.   Email to the new sovereign council doesn't get sent/received though as confirmed by the CXM timeline:-

![image](https://user-images.githubusercontent.com/82212220/135080590-e11cdc62-52a0-486a-aa03-07eb89e028c4.png)

**Comment by MeganCrowthers** [comment]
Tests completed for West 

SNC Enquiry transferred to DDC = EMA003391 Successful Test 
DDC Enquiry transferred to SNC = EMA003384 Successful Test
SNC Enquiry transferred to NCC = EMA003393 Successful Test
NCC Enquiry transferred to DDC = EMA003394 Successful Test
DDC Enquiry Transferred to NCC = EMA003395 @AndyBoatwright to transfer to NCC to confirm successful test
NCC Enquiry Transferred o SNC = EMA003397 Successful Test
DDC Enquiry Transferred to NBC = EMA003398 @AndyBoatwright to transfer case to NBC to confirm successful test
SNC Enquiry Transferred to NBC = EMA003400 Successful Test
NCC Enquiry Transferred to NBC = EMA003399 In this case - email went to Unitary Awaiting Review first of all and case was transitioned to NCC and then transitioned back to NBC. Case transitioned back to Unitary Awaiting Review. 

EMA003401 tested closing the "Window" Upon transition straight away to see outcome - Case was transitioned to One Angel. Case still transitioned. 

EMA003403 tested transition to NNC and DDC. Case does transition twice. Advise staff that is incorrect option is selected they will need to manually contact Sov to make aware.

**Comment by lfayter** [comment]
EN Test - Retested #36 in UAT

EMN000897 - New email sent. Correct sovereign Council and service area allocated. Customer auto response and sovereign council email received. On original sovereign council email, link for 'Kettering' selected. The 'successfully transferred' notice appears. Email to the new sovereign council doesn't get sent/received though.   I've popped below a screenshot of the CXM timeline.  (One slight difference from EMN000881 is it doesn't go to ALC twice only the once):-

![image](https://user-images.githubusercontent.com/82212220/137882403-b4556cbb-a45a-4179-97bf-10df444103d0.png)

**Comment by lfayter** [comment]
EN Test:-

EMN000899 - using the Corby link and EMN000900 - using the Kettering link.  As previous the correct sovereign council, service area was allocated.  Once the links were selected the notification page appears and the CXM dashboard updates, as above, but neither sovereign email was sent/received.

**Comment by Sadie-hub** [comment]
Leeann and I have just retested in UAT, we amended the email in Dynamo to redirect it to our live Customer Services inbox.
There was some very strange activity and Norby attempted to forward the email onto all the links even though we hadn't asked him to. The test cases are below:
EMN000921 - 1/11/21 (10:32)
EMN000922 - 1/11/21 (10:32)
EMN000923 - 1/11/21 (10:36)
We have removed the label 'Signed Off - North' until we can look at this at the next sprint.

**Comment by MeganCrowthers** [comment]
@Sadie-hub it seems that North are experiencing the same issue we had here in West. 
Basically for security, the links are being checked (clicked) when the email is received - however our links, once clicked, initiate a transition within CXM. 
Are you able to raise a call with your IT team to see if there is a way this feature can be removed for all "contactus@" emails?

**Comment by Sadie-hub** [comment]
Thank you Megan, do you have an ICT contact at the West in case our team ask?

**Comment by MeganCrowthers** [comment]
Discussed feature request adding option for service area to be selected.

**Comment by MeganCrowthers** [comment]
First test completed -  EMA003465 - Case sent to South Northants and transferred to OAS. Case transferred to Northampton. Case updated on CXM. 

Second Test - Email sent to South Northants - Case sent to Daventry - Case responded to from the customer - Case closed. Case should have set to Unitary Awaiting review so the enquiry can be manually forwarded - EMA003469

**Comment by MeganCrowthers** [comment]
Case is transitioning as expected however the attachments of the original email is not pulling through correctly. Example EMA003477

**Comment by Sadie-hub** [comment]
North Testing:
EMN000928 - email into East, redirected to Welly, duplicate emails received
EMN000929 - email into Kett, redirected to Corby, duplicate emails received
EMN000930 - form into Kett, redirected to East, duplicate emails received
EMN000932 - form into Corby, redirected to Kett, one email received 
EMN000933 - form into East, redirected to Kett, duplicate emails received
EMN000931 - form into 'hub awaiting review', forwarded to Corby, redirected to Kett, Norby sent to Corby, duplicate emails received
EMN000934 - email into east, redirected to Corby, one email received
EMN000935 - email into 'hub-awaiting location', forwarded to County, redirected to East (pop up says successful) however email failed in CXM (10:42)
EMN000936 - email into Corby, redirected to east, duplicate emails received
EMN000937 - form into Welly, redirected to East, duplicate emails received
EMN000938 - email into Corby, redirected to Welly, duplicate emails received
EMN000939 - form into Welly, redirected to Ketty, duplicate emails received
EMN000940 - form into Corby, redirected to County, email sent to Megan 5 x duplicate emails received (10:58)
EMN000941 - email into Kett, redirected to Welly, duplicate emails received
EMN000928 - email into Kett, redirected to County, email sent to Megan 5 x duplicate emails received (11:05)

**Comment by MeganCrowthers** [comment]
Attempted testing however file does not seem to be uploading. @KevinWhite would you be able to have a look at the file sent in slack to confirm if there is anything missed that is causing this to bork?

**Comment by lfayter** [comment]
North Testing:-
EMN000966 (form) - forwarded to Corby, sovereign email received.  Case closed.  Kettering link selected, reconfirm screen appears, then screen confirming query transfer appears.  Email to Kett received.  Case closed.  

EMN000968 (form) - email into Well.  Case closed.  Redirected to East, reconfirm screen appears, then screen confirming query transfer appears.  Email to East received.  Case closed.  Updated auto customer SLA email with 'I want a reply'.  Email and update sent to East.  **CXM dashboard updates with the customer update, but doesn't show it's been forwarded to East the second time.**  Case closed.

EMN000971 (email) - no location given, case went to 'Hub-awaiting review'.  Email forwarded to leeann.fayter@northnorthants.gov.uk.  Customer SLA email received and email to leeann.fayter received.  Case closed.  Redirected to Corby, reconfirm screen appears, then screen confirming query transfer appears.  Email to Corby received.  Case closed.  On Corby redirect email selected 'County' link.  Reconfirm screen appears, then screen confirming query transfer appears.  Email received by MC.  Case closed.  

EMN000973 (form) - email into East.  Case closed.  Redirected to Corby, reconfirm screen appears, then screen confirming query transfer appears.  Email to Corby received.  Customer SLA email updated with 'I haven't had a reply'.  Email and update sent to Corby.  (As previous CXM dashboard updates with the customer update, but doesn't show it's been forwarded to Corby the second time).  Case closed

**Comment by KellyW66** [comment]
North testing EMN000974 (Form) Email to Kettering, Email received, Case closed. Redirected to East reconfirm screen appears, then screen confirming query transfer appears. Email to East received. Case closed. Updated customer auto response email. which is "Now I am moving to Corby" Email and update sent to Corby. Case closed. link on sovereign email for Corby selected, email to Corby received case closed.

**Comment by Sadie-hub** [comment]
North Testing:
EMN969 - Email into 'hub-awaiting review', forwarded to Welly Norse, redirected to East -  one email, CXM all ok - Success
EMN970 - Email into 'hub - awaiting review' forwarded to County, redirected to Welly - one email, CXM all ok - Success
EMN972 - Email into East, redirected to County, customer chase email sent,- MC confirmed both emails received, CXM dashboard missing second email notification (11:54)
