### ISSUE TITLE
To enable sovereigns to REPLY to forwards and subsequent email will be auto-forwarded to customer email

### ISSUE THREAD

**Issue by AndyBoatwright** [FutureNorthants/VirtualWorker#37]
For example, customer sovereign forward email is received by Daventry; Daventry CIO hits "reply" to that email; currently that would just go back to the hub, but enhancement request is to enable that response to be routed on to the customer.

This would potentially enable reply/response chains to be performed through the bot.

**Comment by MeganCrowthers** [comment]
@AndyBoatwright  I am closing this one down as it is already covered in https://github.com/FutureNorthants/VirtualWorker/issues/55
