### ISSUE TITLE
WNC Contact us form failing to pass into/through bot

### ISSUE THREAD

**Issue by AndyBoatwright** [FutureNorthants/VirtualWorker#40]
Emails received to internal mailbox fine; routed emails to Norb causing error message fire in Cloudwatch logs; don't know why; Kevin needs to check in first instance.

**Comment by KevinWhite** [comment]
![image](https://user-images.githubusercontent.com/960938/112470604-c23cad80-8d62-11eb-872f-d8b1dab48adb.png)

**Comment by MeganCrowthers** [comment]
Duplicate
