### ISSUE TITLE
Replying to Sov Forward instead of replying to customer

### ISSUE THREAD

**Issue by AndyBoatwright** [FutureNorthants/VirtualWorker#41]
CIO hits reply by mistake so they think they're responded to the customer but have actually replied to the bot; needs to flag back up for "unitary review" and reopen in these cases so they can be detected and actioned.

**Comment by KevinWhite** [comment]
In test at the moment

**Comment by MeganCrowthers** [comment]
This I just a test! :)

**Comment by milli07** [comment]
Received
