### ISSUE TITLE
Forward Attachments

### ISSUE THREAD

**Issue by MeganCrowthers** [FutureNorthants/VirtualWorker#5]
<b>Requirement:</b>
As a customer I want to be able to attach document/items to my email and these documents be received by the Sovereign Council that I expect my query to reach
This includes the following attachments:
• .doc, .xls, outlook email
• .pdf
• .jpg, .png
• .Mp3, mp4

<b>User Acceptance</b>
 The customer will email contactus@westnorthants.gov.uk or contactus@northnorthants.gov.uk and a copy of the documents can be viewed in Jadu CXM. If Norbert defines the query with attachments as a non CXM service/sovereign – the customer details are sent to the sovereign service with the documents included as an attachment within the email.

<b>Acceptance criteria</b>
When a query is received - that holds attachments - The MailBot is able to first of all read the attachments to ascertain if holding inappropriate imagery. If it has been defined as holding inappropriate imagery - the customer will be asked to complete a contact us form. If it has not been defined as in appropriate a attachment - a copy of the attachment will go into CXM - and a copy of the attachment and customer details will be sent to sovereign.

**Comment by AndyBoatwright** [comment]
Not sure what you mean by "check for explicitly"?  Do you mean check the attachment is not obscene or expliciit (and therefore needs to be quarantined)?  Presume you would like any emails that come in on an existing case where it has already been forwarded and set to case closed to autoforward to the same sovereign the original was sent to?

**Comment by MeganCrowthers** [comment]
<b>Customer Requirement</b>
As a customer I want to be able to attach document/items on my email and these documents be received by the Sovereign Council that I expect my query to reach
This includes the following attachments:
 •	.doc, .xls, outlook email 
•	.pdf
•	.jpg, .png
•	.Mp3, mp4


<br>
<b>User Acceptance</b>
The customer will email contactus@westnorthants.gov.uk or contactus@northnorthants.gov.uk and a copy of the documents can be viewed in Jadu CXM. If Norbert defines the query with attachments as a non CXM service/sovereign – the customer details are sent to the sovereign service with the documents included as an attachment within the email.
