### ISSUE TITLE
1 week - Automatically record "misdirected" queries forwarded from West to North or vice versa on CXM

### ISSUE THREAD

**Issue by AndyBoatwright** [FutureNorthants/VirtualWorker#58]
In order for this to work correctly, the forwarding to the other council needs to send the original email from the customer, not the template - but we also need to amend the original email from the customer so that it appears to have come from them and been sent directly to the other council - effectively removing any sign it went to the wrong council; current setup won't allow the email to be recorded on CXM.

Current process will require destination mailbox to be determined and these cases will need to be manually handled by staff in the interim.

**Comment by MeganCrowthers** [comment]
<img width="793" alt="Screenshot 2021-07-07 at 09 27 32" src="https://user-images.githubusercontent.com/78955180/124727351-89d27100-df06-11eb-888a-5290931fa3c3.png">

**Comment by MeganCrowthers** [comment]
Best option - If case comes in for opposiing authority - Case status for notification to Unitary Awaiting Review so it can be check by staff member
