### ISSUE TITLE
Forward email to include original email AND latest update from customer (internal process only)

### ISSUE THREAD

**Issue by AndyBoatwright** [FutureNorthants/VirtualWorker#59]
Eg EMA 008033 - forwarded email only containing the 'enquiry details' field (the latest update from customer) - needs to be amended to include the original email field too. Highlighted because it's the local forwarding process not the unitary one.

**Comment by KevinWhite** [comment]
![image](https://user-images.githubusercontent.com/960938/116242063-74e69e00-a75d-11eb-98cc-b01f614c7eae.png)

FFF tag needs updating

**Comment by KevinWhite** [comment]
https://github.com/FutureNorthants/TransferCaseViaEmail/blob/master/Function.cs

**Comment by MeganCrowthers** [comment]
Tested under EMA003021 all details received
Tested under EMA003022 all details received 
Test under EMA003023 contact us - sent to Kettering - forwarded all details received
