### ISSUE TITLE
Intermittent bug - forwards not pulling through entirety of query/missing query details entirely

### ISSUE THREAD

**Issue by AndyBoatwright** [FutureNorthants/VirtualWorker#64]
Sov Forwards not receiving query details (query line blank) or not displaying all the query text, despite it recording on CXM correctly.

Examples to be added

EMN001513 - North case; query shows only the update not the original query..

**Comment by Sadie-hub** [comment]
Checked with AB - we believe this is now resolved

**Comment by MeganCrowthers** [comment]
This has now been resolved and bug has been closed down.

**Comment by MeganCrowthers** [comment]
This can now be closed - forward email address is displayed within CXM.
