### ISSUE TITLE
Bug - NBC Housing Queries not forwarding to outlook inbox

### ISSUE THREAD

**Issue by MeganCrowthers** [FutureNorthants/VirtualWorker#68]
**Bug description**
When an email has been defined as a "Housing" query for NBC Services this is transferring to local process instead of emailing hcs@northampton.gov.uk.

 

**Reference number(s)**
Live: EMA010860, EMA010883, EMA010894, EMA010991, EMA011036

Test: EMA002962

**Bug reproduction**
1. Send an email to contactus@westnorthants.gov.uk regarding a house query for NBC
2. Go into CXM and see Norbert transfer to Local NBC Transition

 

**Expected behaviour**
When an email is sent regarding Housing for NBC services Norbert should forward the query onto hcs@northampton.gov.uk.

 

**Screenshots**
N/A

 

**Additional comments**
In order to get the following to forward to hcs@northampton.gov.uk does HousingCustomerServices Intent need detaching  from NBC_Mailbot_Intents so Norbert refers to District_HousingApplications, District_HousingOptions, District_HousingRent, District_TenancyManagement

Which is set up as the below in DB:

￼
![image](https://user-images.githubusercontent.com/78955180/116980258-ebcfe980-acbd-11eb-9712-551c6f04b896.png)

**Comment by KevinWhite** [comment]
@MeganCrowthers Fix for this is to make all the 'service' values lowercase. As per the below: 

![image](https://user-images.githubusercontent.com/960938/117638944-4b753b80-b17b-11eb-81f5-6b2abfab9e0a.png)

**Comment by MeganCrowthers** [comment]
Tested in UAT under EMA002964 and can confirm it sets out expected behaviour as above
Tested in LIVE under EMA011570 and can cobfirm it sets out expected behaviour as above
