### ISSUE TITLE
Bug - Cases going back into "Awaiting Location Confirmation"

### ISSUE THREAD

**Issue by MeganCrowthers** [FutureNorthants/VirtualWorker#74]
**Bug description**
When a query has been incorrectly forwarded by the bot and therefore manual intervention takes place at the "Hub" and the Sovereign Council/Service is changed - the email is not forwarding to the sovereign and setting the case back to "Awaiting Location Confirmation"

 

**Reference number(s)**
Please provide reference numbers of the error(s) and confirm if this is a LIVE or TEST Reference.

 EMA007848 - West Live
EMA009946 - West Live
EMN000999 - North Live

If you can - please attempt to replicate the error(s) in test and provide the TEST reference number.

 

**Bug reproduction**
Steps to reproduce the behaviour:
1. Complete a contact us form for Sovereign
2. Await for Norbert to forward on
3. Go in and re assign the case to another sovereign

 

**Expected behaviour**
When a CSA has to get involved with the case - Norbert ignores all other previous information provided.

 

**Screenshots**
If applicable, add screenshots to help explain the issue.

 

**Additional comments**
Add any other commentary about the problem here.

**Comment by MeganCrowthers** [comment]
Further examples from Kelly EMN002024/ EMN002026/ EMN002116 / EMN001869

**Comment by KevinWhite** [comment]
![image](https://user-images.githubusercontent.com/960938/117954554-097cfe80-b30f-11eb-8ee3-a0fb00b20487.png)

**Comment by MeganCrowthers** [comment]
Tested Cases in UAT (WEST) 

- [ ] EMA002992 email sent - bot defined as South Northants Business Rates - Unitary Being Reviewed set to Dev/Business Rates - sent to department.

- [ ] EMA002994 - email sent with no location - set to Unitary Awaiting Review - changed to NCC default (not found) - Sent to department - received by department. 

- [ ] EMA002995 - email sent with location - case closed - responded as customer - case set to unitary awaiting review. Set to Dev - Benefits - received by sovereign

- [ ] EMA002996 - email sent without location - manually pushed to awaiting review and forward - case forwarded to forward however holding old templates (this will be fixed under another bug) 

- [ ] EMA002997 - email sent without location - moved to internal process (awaiting review) forwarded the case. Cased closed and sent. Case was then put into Unitary Awaiting Review and sent to South Northants Events - case sent and closed. 
- [ ] EMA002998 contact us sent with location - sent to correct service area - case closed. Customer responded - sent to soverign - case set to being reviewed unitary case soverign set to SNC but area change to council tax - sent and received by Soverign

**Comment by MeganCrowthers** [comment]
North Tests

EMN000538 - tested forwarding to Coventry after bot sent to Kettering - all worked
EMN000539 - tested forward email to Wellingborough from case in ALC - all worked
EMN000540 - tested sending email from contact us - changed as forwarded to Wellingborough - all worked

**Comment by joanne-debug** [comment]
Thank you Megan – we were happy too with our testing yesterday.  There was one comment we added to the chat regarding this – chat about it at the scrum 😊
Joanne

**Comment by MeganCrowthers** [comment]
retested for WNC 
EMA003018 - case sent to Northampton and forwarded case - received 
EMA003020 - case sent to Dav - moved to forward - received (contactus)
EMA003019 - Case moved from south Northants (defined by bot) case moved moved to Dav - case sent.

**Comment by MeganCrowthers** [comment]
confirmed tested in West EMA012152 - transitioned over 
confirmed tested North EMN002468 - transitioned over

**Comment by MeganCrowthers** [comment]
@KevinWhite can you look into EMN000545 (UAT) 

Live case in North EMN002505 has been replicated.

* Bug reproduction
Steps to reproduce the behaviour:

- [ ] Send email to contactus@north with no address
- [ ] Await for Norbert to send Location Confirmation and provide postcode out of area
- [ ] Norbert sets query to Unitary Awaiting Review (correct) 
- [ ] Forward query to another department through Hub Process
- [ ] See Error - Case does not close

I can confirm customers are still receiving the emails.

**Comment by lfayter** [comment]
NNC Live Testing:-
EMN002571 - case raised and bot sent to Kettering, hub then forwarded to ENC using email2 field (manually typed). No email was received at ENC and case is stuck in 'Awaiting Location Confirmation' status.
EMN002572 - Case raised and bot sent to ENC, hub forwarded to Kettering using email1 field (Sovereign drop down). Email successfully received by Kettering and case successfully closed.
EMN002573 - Case raised and bot sent to ENC, hub forwarded to personal email using email2 field (manually typed). No email was received  and case is stuck in 'Awaiting Location Confirmation' status.

**Comment by KevinWhite** [comment]
@lfayter There's a bug in the email2 process, working on a fix for that.

**Comment by lfayter** [comment]
Closed in error, reopened.

**Comment by lfayter** [comment]
NNC Testing in test environment - a number of cases created and issues identified.  Customer telephone number not appearing on forwarded email (issue highlighted on teams - KW looking into).   When cases forwarded to customerservices.enc inbox from our CXM test system they were failing to arrive.  Issue logged with our ICT team as we believe this maybe an issue our end.  However, cases were closing and not going back to ALC.

**Comment by lfayter** [comment]
NNC Testing (live) - A number of test cases were raised in our live environment on the 21/5/21 and all were successful.
