### ISSUE TITLE
Missing 'Comment - Sent to Email' Field 

### ISSUE THREAD

**Issue by milli07** [FutureNorthants/VirtualWorker#80]
**Bug description**
A clear and concise description of what the bug is, what is happening and what the impact is. NORTH - the comments field which tells an advisor where the case has been forwarded to is not appearing in a certain scenario. The scenario is that a case is created in CXM, the BOT identifies the wrong sovereign, the Hub manually change the sovereign, the customer sends an update, the BOT sends the new update to the relevant sovereign (last chosen one on CXM) however the Comments field is not present to prove where it has been sent. The impact is that staff are having to phone sovereigns to see if cases have been forwarded due to the fact that bug #74 has meant they have not been forwarding, so when the fix for #74 is in place we need to have visual proof of where the case has been sent or not to prevent manual checking. 

**Reference number(s)**
EMN000535 in LIVE

 

If you can - please attempt to replicate the error(s) in test and provide the TEST reference number.

 

**Bug reproduction**
Steps to reproduce the behaviour:
1. Complete a Contact Us form
2. From the Hub change the Sovereign in CXM
3. Send a customer update on the case
4. See in the case on CXM that the top Comments field, which shows where the case has been forwarded to, is not present. 

 

**Expected behaviour**

1. Customer to complete Contact us form
2. If BOT chooses wrong sovereign  (A) the Hub wil reallocate to the correct sovereign (B)
3. Customer sends an update to the case
4. BOT sends the update to the latest sovereign (B)
5. The comments field to be displayed showing the trail for point 4 in CXM so that advisors can see where the update has been sent to. (this bit is missing at the moment)
 

**Screenshots**
There is one on unitary chat but i can't copy and paste from there and my snipping tool won't open either

**Additional comments**
This will impact us monitoring the Bug fix for #74

**Comment by MeganCrowthers** [comment]
This can now be closed - forward email address is displayed within CXM.
