### ISSUE TITLE
Bug - Norbert using address data from contact form instead of address within the query

### ISSUE THREAD

**Issue by MeganCrowthers** [FutureNorthants/VirtualWorker#81]
**Bug description**
When an auto response is responded (where norbert has defined Sovereign and Service Area) Norbert is reading address details instead of enquiry details on contact us form. 

 **Reference number(s)**
EMA003049
EMA003047
 

If you can - please attempt to replicate the error(s) in test and provide the TEST reference number.

 

**Bug reproduction**
Steps to reproduce the behaviour:
1. Complete contact us form, set the address and within the enquiry details ask a query that is outside your address' sovereign - for example set your address as 112 Station Road Cogenhoe but ask about Parking In Daventry 
2. Await for bot to submit query to sovereign council (Dav in this instance) 
3. Await for Auto Response to be received 
4. Respond to the Auto Response
5. See Error - Norbert sets Sovereign forward - however forwards to address Sovereign not enquiry Sovereign 

 

**Expected behaviour**
When you respond to a query, your enquiry is redirected to the legacy your enquiry is related to.

 

**Screenshots**
If applicable, add screenshots to help explain the issue.

 

**Additional comments**

User Story: 

As a customer service manager, I want follow up customer emails/contact to be automatically directed to the sovereign council that the initial contact went to. So that it can be handled by the right team. & so that the right team has any follow up information. 

Acceptance criteria: 

If a customer provides an update to their enquiry or responds, the bot is to forward the enquiry to the sovereign council that received their original contact.

Information about where the bot has sent the email should be displayed in the CXM/ case timeline (within the email comments field)

**Comment by MeganCrowthers** [comment]
@KevinWhite examples for this one:

- West Example (UAT) - EMA003137
- North Example (UAT) - Cant replicate in North Test @Sadie-hub have you got an example?

**Comment by MeganCrowthers** [comment]
<img width="732" alt="Screenshot 2021-07-07 at 09 28 26" src="https://user-images.githubusercontent.com/78955180/124727136-58f23c00-df06-11eb-88a3-c4e7c252c570.png">

**Comment by AndyBoatwright** [comment]
Needs priority of which one takes precedence in the checking process as there are pros and cons of either approach, so this needs to be understood

**Comment by MeganCrowthers** [comment]
Testing completed for West: EMA003144, EMA003145, EMA003146
Testing complete for North: EMN000724, EMN000725, EMN000726, EMN000727

**Comment by Sadie-hub** [comment]
Test EMN00743 - Didn't work - Norby initially correctly forwarded to Corby, customer update received and Norby incorrectly forwarded to ENC - looks like he's still picking up address from customer data

**Comment by MeganCrowthers** [comment]
@KevinWhite another example EMN005450 in Live. Issue happens when agent manually amends the sov/service

**Comment by Sadie-hub** [comment]
Leeann and I have raised identical cases in UAT & Live. They are not behaving the same at the moment, we will add these test cases to GitHub for Kevin’s reference.

UAT journey – EMN821:
1.	Query originally forwarded to correct Sovereign (ENC)
2.	Customer responds to confirmation email and it moves to ‘Hub – Awaiting Review’

Live journey – EMN6145:
1.	Query originally forwarded to correct Sovereign (ENC)
2.	Customer responds to confirmation email and bot auto sends it to Sovereign using the form address NOT the query address

If it has been decided that all updated cases (where customer has responded to confirmation email) will go to ‘Hub – Awaiting Review’ (as it is currently set up in UAT), please would you be able to amend the process map in Git Hub as it currently states that we want the update to auto forward to the original Sovereign.

**Comment by Sadie-hub** [comment]
It appears that the Bot is no longer forwarding updates onto Sovereign Councils (rightly or wrongly). 
Example case EMN005774 :

- Case was created 14/7/21 (16:30)
- Case was updated by customer on 28/7/21 (11:41) and became stuck in ALC
- Hub attempted to forward to sovereign (oas) on 28/7/21 (12:52) but this failed

We are currently having to manually forward (via outlook) any cases that are updated by the customer.

**Comment by lfayter** [comment]
NNC Live Testing:- 
EMN007017 - Responded to customer auto response, case went to 'Hub-Awaiting Review'.  Moved case to 'Hub-Being Reviewed', tried forwarding case to customerservices.enc@ - no email received, case failed to close and went back to 'Hub - Awaiting Review'.
EMN007019 - Responded to customer auto response, case went to 'Hub-Awaiting Review'.  Moved case to 'Hub-Being Reviewed', tried 'forward to' Kettering.  No update on dashboard to confirm an email had been sent.  (Checked with KBC who confirmed they did receive the update their end).  Case failed to close and went back to 'Hub - Awaiting Review'.

**Comment by lfayter** [comment]
NNC Live Testing:-  Retested
EMN007176 - Responded to customer auto response, case went to 'Hub-Awaiting Review'. Moved case to 'Hub-Being Reviewed', tried forwarding case to customerservices.enc@ - no email received, case failed to close and went back to 'Hub - Awaiting Review'.

**Comment by lfayter** [comment]
EMN007188 - Responded to customer auto response, case went to 'Hub-Awaiting Review'. Moved case to 'Hub-Being Reviewed', tried 'forward to' Kettering. No update on dashboard to confirm an email had been sent.  Case failed to close and went back to 'Hub - Awaiting Review'.

**Comment by Sadie-hub** [comment]
Testing EMN7338 - Customer Journey:
Original query received and correctly allocated to sovereign area within body of text - conf email received, sov email received & case closed.
Customer responds to conf email, case moves to 'Hub - awaiting review', CSA fwd to sov - email received (original email as attachment), path shows on CXM dashboard & case closed
Customer responds to conf email second time, case moves to 'Hub - awaiting review', CSA fwd to sov - email received (original email as attachment), **_no path displayed_** on CXM dashboard, case closed.

**Comment by AndyBoatwright** [comment]
@Sadie-hub this needs to be raised as an additional enhancement request, as its not in scope for this actual bug

**Comment by Sadie-hub** [comment]
I'm not sure but think this may get covered in #91/#174, If not will raise as an enhancement
