### ISSUE TITLE
Feature - Enable Norbert to show you when he has forwarded an email in CXM

### ISSUE THREAD

**Issue by MeganCrowthers** [FutureNorthants/VirtualWorker#82]
**User Story/Requirement**
When a customer responds to a query, as the Email Hub, I would like Norbert to show us he has forwarded a case instead of auto closing.

 

**Is the feature request related to an existing problem? Please describe.**
N/A

 

**Describe the solution you want to be used**
When a customer responds to an auto response - instead of forwarding the query and closing it Norbert tells you where he has forwarded it before closing it.

 

**Describe alternatives you have considered**
Take "closed" as is - that it has been forwarded 

 

**Additional comments**
N/A
 

**Acceptance Criteria***
Outline how this requirement will be formerly signed off and by whom following successful testing.

**Comment by MeganCrowthers** [comment]
@KevinWhite examples for this one:
North UAT: EMN000722
West UAT: EMA003138 (works for contact us - EMA003139)

**Comment by MeganCrowthers** [comment]
<img width="793" alt="Screenshot 2021-07-07 at 09 28 17" src="https://user-images.githubusercontent.com/78955180/124727199-67d8ee80-df06-11eb-8167-be29456adac8.png">

**Comment by AndyBoatwright** [comment]
For example, customer sovereign forward email is received by Daventry; Daventry CIO hits "reply" to that email; currently that would just go back to the hub, but enhancement request is to enable that response to be routed on to the customer.

This would potentially enable reply/response chains to be performed through the bot.

**Comment by Sadie-hub** [comment]
EMN000745 - no display of 'forwarded to' on CXM timeline after customer sent in an update *No email received for update either

**Comment by MeganCrowthers** [comment]
@KevinWhite example for West in Test is EMA003189 - Case closes staff would like to see forwardee email address that this has been sent to instead of "Closed". To replicate email contact-us with query. Change status to Unitary Being Reviewed and change to another sovereign. As the customer - respond to update us email. Case updates and closes. Does not show who it has been forwarded to.

**Comment by MeganCrowthers** [comment]
@KevinWhite example for North in LIVE is EMN005672. Unable to replicate in test as queries are getting stuck in ALC.
To replicate email contact us. Change status to Unitary Awaiting Review, then being review and change sov. As customer respond to updateus email. Case updates with customers query. Case closes. Does not show who it has been forwarded to so team are unsure if it has been recieved by sov.

**Comment by MeganCrowthers** [comment]
This has been tested and has been completed
