### ISSUE TITLE
Enable Norby to be able to identify a location using the subject line in an email

### ISSUE THREAD

**Issue by Sadie-hub** [FutureNorthants/VirtualWorker#85]
**User Story/Requirement**
When a customer completes a Contact Us email and specifies their location in the subject line, I would like Norby to be able to allocate a Sovereign Council.

 

**Is the feature request related to an existing problem? Please describe.**
N/A

 

**Describe the solution you want to be used**
Norby to be able to identify customers location using the subject line as well as the body of text.

 

**Describe alternatives you have considered**
Manage manually

 

**Additional comments**
If possible to be included in the next sprint.

 

**Acceptance Criteria***
Outline how this requirement will be formerly signed off and by whom following successful testing.

**Comment by Sadie-hub** [comment]
Address in subject line - Example case in UAT EMN000598

**Comment by MeganCrowthers** [comment]
<img width="793" alt="Screenshot 2021-07-07 at 09 28 02" src="https://user-images.githubusercontent.com/78955180/124727271-77f0ce00-df06-11eb-9cdc-a313e76b0fb9.png">

**Comment by Sadie-hub** [comment]
Tested 12/7/2021 - see Teams thread

**Comment by Sadie-hub** [comment]
Recreated case with identical details as above (EMN007064) this time it worked fine EMN007291 (11:43).
Recreated case with identical details as above (EMN007061) this time it worked fine EMN007294 (11:48).
