### ISSUE TITLE
Feature - BOT to know difference between Area and County 

### ISSUE THREAD

**Issue by MeganCrowthers** [FutureNorthants/VirtualWorker#9]
**User Story/Requirement**
As a customer I want my query to be sent to the correct Sovereign/Authority despite the mention of "Northamptonshire" in my query so that it can be dealt with.

**Acceptance Criteria***
Norbert should ignore "Northamptonshire" as an identifiable location.

Norbert will first check to see if the enquiry is relating to a County Service. If the query is relating to a County Service, the customers query is forwarded to Angel Square. If the enquiry is not relating to a County Service then the customers enquiry is forwarded to the customers sovereign council (Postcode/Area).

 

**Is the feature request related to an existing problem? Please describe.**
N/A

 

**Describe the solution you want to be used**
When a customers sends a enquiry specifying their Area and County - Norbert sets Area as "Master" 

 

**Describe alternatives you have considered**
Can go to Unitary awaiting review if more than 1 "location" provided.

 

**Additional comments**

Example EMA001947, if the area is provided - ignore the  county (i.e I live in Daventry, **_Northamptonshire_**)

Addendum - where a customer is querying something where the county is being referred to (i.e. "North /West Northamptonshire"),. the bot should be looking to only route to Northampton if specific mention is made of "northampton" and not any phrase that includes it (such as the above).

When a customers sends an enquiry specifying their Area and County - Norbert sets Area as "Master" to stop queries diverting to Angel Square. For example: EMA002956

**Comment by AndyBoatwright** [comment]
Addendum for location specification - requires specific logic to determine; for example, if customer says "When I used to live in Northampton, my bins were collected on a Weds; now I live in Towcester..." the bot needs to know to ignore the first location used and trigger on the second; unsure how we'd approach this.

**Comment by Sadie-hub** [comment]
Testing EMN746 & 743 - Norby is successfully ignoring 'Northamptonshire' and directing to correct sovereign

**Comment by lfayter** [comment]
NNC Live Testing:-
EMN007036 - Form submission.  Planning query, 'Northamptonshire' specified in enquiry details.  'Thrapston' address selected as customer address.  Correct sovereign Council allocated (EN).   All emails received.  Case closed. 
EMN007037 - Email submission.  Planning query, 'Northamptonshire' specified in enquiry details.  No address details specified.  Case went to ALC.  Replied to auto response.  Correct sovereign Council allocated (EN).   All emails received.  Case closed. 
EMN007039 - Form submission.  Library query, 'Northamptonshire' specified in enquiry details.  'Thrapston' address selected as customer address.  Correct sovereign Council allocated (OAS), email forwarded.   Case closed.
